"""
Quick validation script for Streamlit observability dashboard.

Checks that all pages can be imported and key dependencies are available.
"""
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent

def validate_imports():
    """Validate all dashboard pages can be imported."""
    print("Validating dashboard imports...")

    errors = []

    # Check Streamlit
    try:
        import streamlit as st
        print(f"[OK] Streamlit {st.__version__}")
    except ImportError as e:
        errors.append(f"[ERROR] Streamlit not installed: {e}")

    # Check pandas
    try:
        import pandas as pd
        print(f"[OK] Pandas {pd.__version__}")
    except ImportError as e:
        errors.append(f"[ERROR] Pandas not installed: {e}")

    return errors

def validate_files():
    """Validate all dashboard files exist."""
    print("\nValidating dashboard files...")

    errors = []

    required_files = [
        "app/Home.py",
        "app/pages/01_Trace_Explorer.py",
        "app/pages/02_Confidence_Analysis.py",
        "app/pages/03_Calibration_Dashboard.py",
        "app/pages/04_Planner_Review.py",
        "app/README.md"
    ]

    for file_path in required_files:
        full_path = PROJECT_ROOT / file_path
        if full_path.exists():
            print(f"[OK] {file_path}")
        else:
            errors.append(f"[ERROR] Missing: {file_path}")

    return errors

def validate_data_sources():
    """Validate key data files exist."""
    print("\nValidating data sources...")

    errors = []

    data_files = [
        ("data/traces/trace_index.json", False),  # Generated by pipeline
        ("data/forecasts_ranked.json", False),    # Generated or checked-in sample data
        ("data/calibration_report.json", False)   # Generated by pipeline
    ]

    for file_path, required in data_files:
        full_path = PROJECT_ROOT / file_path
        if full_path.exists():
            print(f"[OK] {file_path}")
        elif required:
            errors.append(f"[ERROR] Required file missing: {file_path}")
        else:
            print(f"[SKIP] {file_path} (optional, generated by pipeline)")

    return errors

def main():
    print("=" * 60)
    print("Dashboard Validation")
    print("=" * 60)

    all_errors = []

    all_errors.extend(validate_imports())
    all_errors.extend(validate_files())
    all_errors.extend(validate_data_sources())

    print("\n" + "=" * 60)

    if all_errors:
        print("VALIDATION FAILED")
        print("=" * 60)
        for error in all_errors:
            print(error)
        return 1
    else:
        print("VALIDATION PASSED")
        print("=" * 60)
        print("\nTo launch dashboard:")
        print("  python -m streamlit run app/Home.py")
        print("\nDashboard will open at: http://localhost:8501")
        return 0

if __name__ == "__main__":
    sys.exit(main())
